### ISSUE TITLE
Fit more of the mana cost onto a single line

### ISSUE THREAD

**Issue by mcandre** [fklingler/mtgproxy#24]
Love the tool, thank you for posting!

Can we soften the layout in order to keep more of the mana cost on a single line?

The example Bolas's Citadel card has plenty of leftover room for the complete mana cost, but it's actually spilling onto a second line.

**Comment by fklingler** [comment]
This has now been fixed, thanks for the suggestion!

`{` and `}` have been removed for simple mana symbols (numbers and colors), but are staying for complex ones like phyrexian mana.

![image](https://github.com/fklingler/mtgproxy/assets/282439/71716ecf-d27d-4053-b1ec-8e9d727d1683)

![image](https://github.com/fklingler/mtgproxy/assets/282439/12bedd0a-0524-4021-92f5-b40317710aba)

If the name and the mana cost can't fit, the mana cost will be moved to a second line, with right alignment

![image](https://github.com/fklingler/mtgproxy/assets/282439/d0539d89-24d1-47f1-9070-6b4478060be7)
