### ISSUE TITLE
Token Support?

### ISSUE THREAD

**Issue by zjsealeypayne** [fklingler/mtgproxy#25]
Kia ora!

Is there a way to print tokens off with this software? If this not the correct way to ask I apologise; I am not very familiar with GitHub.

**Comment by fklingler** [comment]
Hi!

This has now been added, thank you for the suggestion.

You can display tokens simply by searching their names, but in some cases it will not be enough, as many different tokens share the same name.
To allow you searching for a specific token (or specific variant of a card, in some weird cases like [Very Cryptic Command](https://scryfall.com/search?as=grid&extras=true&lang=any&order=name&q=very+cryptic+command&unique=cards)), you can now add a `?` at the beginning of a line (well after the card count), and the card search will use Scryfall advanced syntax.
An exemple is provided as a placeholder in the card list textarea.

Probably not what you want: `2x Soldier`
![image](https://github.com/fklingler/mtgproxy/assets/282439/7e1d3522-7799-4a9a-bfd0-cba9ae578568)

But you can do instead: `2x ? Soldier type:token o:haste`
![image](https://github.com/fklingler/mtgproxy/assets/282439/291e329b-8feb-439c-a1b0-9c4c91ac69e7)


Some more features have been added that could be useful for you, notably the possibility to manually edit text content of cards.

**Comment by zjsealeypayne** [comment]
This is so awesome, thank you!

**Comment by zjsealeypayne** [comment]
Sorry for the double post, I just properly read your reply and tested it, all of these new features are actually so great. I will no longer have to double sleeve my proxies for double faced cards, and the scryfall search syntax feature is perfect (and how i kinda tried to brute force the tokens just in case they were a hidden feature initially). Also, the "manually edit" feature will allow me to make up little detailed copy tokens for cards like Gruff Triplets. This was a great tool that is now basically perfect for my needs, so thank you again :)

**Comment by fklingler** [comment]
I’m happy it’s useful for you! :)
If you think of other improvements ideas, don’t hesitate to post them as new issues here on GitHub.

**Comment by zjsealeypayne** [comment]
Hello again,

I went to print off a deck and have noticed that not every double faced card is allowing me to pop it on one face. It appears that modal DFCs are supported but transforming DFCs aren't. Is this intended behaviour?

**Comment by fklingler** [comment]
Hi, this is not intended. I will fix it!

**Comment by fklingler** [comment]
This is fixed :) thank you for the feedback.

**Comment by zjsealeypayne** [comment]
thanks again <:
